# Generated by Django 5.0.1 on 2025-11-26 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("full_name", models.CharField(max_length=100)),
                ("fingering", models.CharField(max_length=20)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("major", "Major"),
                            ("minor", "Minor"),
                            ("seventh", "Seventh"),
                            ("major_seventh", "Major Seventh"),
                            ("minor_seventh", "Minor Seventh"),
                            ("suspended", "Suspended"),
                            ("augmented", "Augmented"),
                            ("diminished", "Diminished"),
                            ("power", "Power Chord"),
                            ("barre", "Barre Chord"),
                            ("other", "Other"),
                        ],
                        default="major",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="chord_diagrams/"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("artist", models.CharField(max_length=200)),
                ("album", models.CharField(blank=True, max_length=200)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("normalized_title", models.CharField(blank=True, max_length=200)),
                ("normalized_artist", models.CharField(blank=True, max_length=200)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["artist", "title"],
                "unique_together": {("title", "artist")},
            },
        ),
        migrations.CreateModel(
            name="Tab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("chords_used", models.CharField(blank=True, max_length=500)),
                ("strumming_pattern", models.CharField(blank=True, max_length=200)),
                (
                    "tuning",
                    models.CharField(
                        choices=[
                            ("standard", "Standard (EADGBE)"),
                            ("drop_d", "Drop D (DADGBE)"),
                            ("half_step_down", "Half Step Down"),
                            ("full_step_down", "Full Step Down"),
                            ("open_g", "Open G"),
                            ("open_d", "Open D"),
                            ("dadgad", "DADGAD"),
                            ("other", "Other"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("capo", models.IntegerField(default=0)),
                ("tempo", models.IntegerField(blank=True, null=True)),
                ("source_url", models.URLField(blank=True)),
                ("source_site", models.CharField(blank=True, max_length=100)),
                ("quality_score", models.FloatField(default=0.0)),
                ("rating_count", models.IntegerField(default=0)),
                ("date_fetched", models.DateTimeField(auto_now_add=True)),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tabs",
                        to="project.song",
                    ),
                ),
            ],
            options={
                "ordering": ["-quality_score", "-rating_count"],
            },
        ),
        migrations.CreateModel(
            name="UserFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_saved", models.DateTimeField(auto_now_add=True)),
                ("practice_time", models.IntegerField(default=0)),
                ("last_practiced", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("is_mastered", models.BooleanField(default=False)),
                (
                    "tab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="project.tab",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_saved"],
                "unique_together": {("user", "tab")},
            },
        ),
    ]
