# Generated by Django 5.0.1 on 2025-12-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "instructions",
                    models.TextField(help_text="Step-by-step instructions"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("finger", "Finger Exercises"),
                            ("chord_transition", "Chord Transitions"),
                            ("picking", "Picking Patterns"),
                            ("strumming", "Strumming Patterns"),
                            ("scales", "Scales"),
                            ("stretching", "Hand Stretching"),
                            ("rhythm", "Rhythm Training"),
                        ],
                        default="finger",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("duration_minutes", models.IntegerField(default=5)),
                (
                    "tab_notation",
                    models.TextField(blank=True, help_text="Optional tablature"),
                ),
                ("tips", models.TextField(blank=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "chords",
                    models.ManyToManyField(
                        blank=True, related_name="exercises", to="project.chord"
                    ),
                ),
            ],
            options={
                "ordering": ["category", "difficulty", "name"],
            },
        ),
    ]
