# Generated by Django 5.0.1 on 2025-12-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_exercise"),
    ]

    operations = [
        migrations.AddField(
            model_name="tab",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
    ]
