# Generated by Django 5.0.1 on 2025-12-10 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_tab_difficulty"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="song",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="song",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="song",
            name="normalized_artist",
        ),
        migrations.RemoveField(
            model_name="song",
            name="normalized_title",
        ),
    ]
